Pathing
ClearSlide/Fantastic-Transcoder pull request #12
Opened 2017-08-19 17:14 UTC by jonathanjtan

i hate creep block

2017-08-22 16:53 UTC, gabinante commented on poll.py
> +                Path = 'null'
Now you're changing what's committed to dynamo and the other functions expect. so we can't merge this without breaking stuff.

2017-08-22 16:54 UTC, gabinante commented on poll.py
> +                Path = 'null'
FYI this was put in place because you can't put empty strings in dynamo. kill me

2017-08-22 17:18 UTC, gabinante commented on poll.py
> +                Path = 'null'
Also, I don't think "is None" always evaluates properly. I think I tried this before I did it the current way.

2017-08-22 17:33 UTC, gabinante requested changes
Either no, or you need to change what all the other functions expect when 'NULL' is logged to dynamoDB.

2017-08-23 19:31 UTC, jonathanjtan commented
i'm silly i fixed this in my other pr

2017-08-23 19:31 UTC, closed without merging